### ISSUE TITLE
⌚Sending Bare Meshes Takes Forever

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sketchup#51]
### Expected vs. Actual Behavior

Meshes that are not in any group/component takes significantly longer. Especially geometries that are a bit complex takes forever to send.

![SketchUp_4nxGqQ2bdL](https://user-images.githubusercontent.com/51519350/179924513-a112b5ef-5d0c-4bc3-8379-db35114a8473.gif)

### Reproduction Steps & System Config (win, osx, web, etc.)

Download the file from below link, send it to Speckleverse🟦.

https://drive.google.com/file/d/17jwqMrPap31us8onEcpsAZwmu3KT_-L4/view?usp=sharing

### Proposed Solution (if any)

Group meshes/faces by material or layer (maybe this can be in **Advanced Settings** too). 

#### Optional: Affected Projects

💄DUI Makeover for Sketchup Connector

**Comment by izzylys** [comment]
this is due to the fact that in sketchup, you don't really have meshes but you have faces which are each flat ngons. in a component definition / group, I am assuming it is safe to group all faces with the same material into one mesh. if you haven't grouped your faces, each face goes out as an individual mesh

as bilal says, the solution would prob be to combine all touching faces with the same material with an option to turn this behaviour off in advanced settings (bc there are prob cases where this doesn't work as the user expects and they should be able to configure it)
